accounts/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path('',view_register,name='register'),
    path('activate/<uid64>/<token>/',activate,name='activate'),
    path('login/',view_login,name='login'),
    path('logout/',view_logout,name='logout'),
    path('forgotpassword/',view_forgotpassword,name='forgotpassword'),
    path('forgotpassword_validate/<uid64>/<token>/',reset_password_validate,name='reset_password_validate'),
    path('reset_password/',view_resetpassword,name='resetpassword'),
    path('dashboard/',view_dashboard,name='dashboard'),
    path('edit_profile/',view_editprofile,name='editprofile'),
    path('myOrders/',view_myorders,name='myOrders'),
    path('orderdetail/<int:order_number>/',view_orderdetail,name='orderdetail'),
    path('change_password/',view_changepassword,name='change_password'),
    path('pdfupdate/',view_pdfupdate,name='pdfupdate'),
    path('add/', add_location, name='add_location'),
    path('suggest/', suggest_location, name='suggest_location'),
    path('load-states/', load_states, name='load_states'),
    path('load-cities/', load_cities, name='load_cities'),
    path('location/',create_location ,name='location'),
    path('loc/',view_location,name='location'),
    path('get-states/',get_states,name='get_states'),
    path('get-cities/',get_cities,name='get_cities'),
    path('drop/',dependent_field,name='dependent_field'),
    path('dynamic-form/', dynamic_form, name='dynamic_form'),

    

]

greatKartt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('great.urls')),
    path('',view_home,name='home'),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('kart/',include('kart.urls')),
    path('orders/',include('orders.urls')),
    path('chart/',view_chart)

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

kart/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('addkart/<int:product_id>/',add_kart,name='add_to_kart'),
    path('cart/',cart_details,name='cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',remove_cart_item,name='remove_item'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',remove_cart,name='remove_cart'),
    path('checkout/',view_checkout,name='checkout'),
]

accounts/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

class MyAccountManager(BaseUserManager):
    def create_user(self,first_name,last_name,username,email,password=None):
        if not email:
            raise ValueError('user must have an email')
        if not username:
            raise ValueError('user must have an username')


        user=self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,first_name,last_name,username,email,password):
        user=self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_active=True
        user.is_admin=True
        user.is_staff=True
        user.is_superadmin=True
        user.save(using=self._db)
        return user


class account(AbstractBaseUser):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    username=models.CharField(max_length=100,unique=True)
    phone=models.CharField(max_length=100)
    email=models.EmailField(max_length=100,unique=True)

    # required
    date_joined=models.DateTimeField(auto_now_add=True)
    last_login=models.DateTimeField(auto_now_add=True)
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=False)
    is_superadmin=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)

    objects=MyAccountManager()


    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['first_name','last_name','username']

    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    def __str__(self):
        return self.email


    def has_perm(self,perm,obj=None):
        return self.is_admin

    def has_module_perms(self,add_label):
        return True 

class UserProfile(models.Model):
    user=models.OneToOneField(account,on_delete=models.CASCADE)
    address_line_1=models.CharField(blank=True,max_length=100)
    address_line_2=models.CharField(blank=True,max_length=100)
    state=models.CharField(blank=True,max_length=100)
    city=models.CharField(blank=True,max_length=100,)
    country=models.CharField(blank=True,max_length=100)
    profile_picture=models.ImageField(blank=True,upload_to='userprofile/')


    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1}{self.address_line_2}'




class Country(models.Model):
    name = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.name

class State(models.Model):
    name = models.CharField(max_length=100,null=True,blank=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100,null=True,blank=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render
from .forms import *
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from kart.models import *
from kart.views import _kart_id
import requests
from django.shortcuts import get_object_or_404
from accounts.models import *
from orders.models import *
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def view_register(request):
    if request.method=='POST':
        forms=UserForms(request.POST)
        if forms.is_valid():
            first_name=forms.cleaned_data['first_name']
            last_name=forms.cleaned_data['last_name']
            email=forms.cleaned_data['email']
            username=email.split('@')[0]
            password=forms.cleaned_data['password']
            phone=forms.cleaned_data['phone']
            user=account.objects.create_user(first_name=first_name,last_name=last_name,username=username,email=email,password=password)
            user.phone=phone
            user.save()
            current_site=get_current_site(request)
            mail_subject='Account Verification'
            message=render_to_string('accounts/account_verification.html',{'user':user,
                'domain':current_site,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token((user))})
            to_email=email
            send_email=EmailMessage(mail_subject, message,to=[to_email])
            send_email.send()
            # messages.success(request,'registeration has been successfully done!')
            return redirect('/accounts/login/?command=verification&email='+email)
    else:
        forms=UserForms()
    context={'forms':forms}
    return render(request,'accounts/register.html',context)

def activate(request,uid64,token):
    try:
        uid=urlsafe_base64_decode(uid64).decode()
        user=account._default_manager.get(pk=uid)
    except (ValueError,TypeError,OverflowError,account.DoesNotExist):
        user=None
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active=True
        user.save()
        return redirect('login')
    else:
        return render(request,'accounts/register.html')


def view_login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        user=auth.authenticate(email=email,password=password)
        if user is not None:
            try:
                cart=Kart.objects.get(kart_id=_kart_id(request))
                cartitemexist=Kart_item.objects.filter(cart=cart).exists()
                if cartitemexist:
                    cart_item=Kart_item.objects.filter(cart=cart)
                    ex_variation=[]
                    ex_id=[]
                    for item in cart_item:
                        Variations=item.variations.all()
                        ex_variation.append(list(Variations))
                        ex_id.append(item.id)
                   
                
                    cart_item_login=Kart_item.objects.filter(user=user)
                    ex_var=[]
                    exx_id=[]
                    for item in cart_item_login:
                        Variationss=item.variations.all()
                        ex_var.append(list(Variationss))
                        exx_id.append(item.id)

                    for pr in ex_variation:
                        if pr in ex_var:
                            Index=ex_var.index(pr)
                            var_id=exx_id[Index]
                            cart_itemm=Kart_item.objects.get(user=user,id=var_id)
                            cart_itemm.quantity+=1
                            cart_itemm.user=user
                            cart_itemm.save()
                        else:
                            kartt=Kart_item.objects.filter(cart=cart)
                            for item in kartt:
                                item.user=user
                                item.save()
            except:
                pass
            auth.login(request,user)
            try:
                url=request.META.get('HTTP_REFERER')
                query=requests.utils.urlparse(url).query
                params=dict(x.split('=')for x in query.split('&'))
                if 'next' in params:
                    nextpage=params['next']
                    return redirect(nextpage)
            except:
                return redirect('dashboard')
        else:
            return redirect('login')

    return render(request,'accounts/login.html')       

@login_required(login_url='login')
def view_logout(request):
    auth.logout(request)
    messages.error(request,'user logged out successfully!')
    return redirect('login')

def view_forgotpassword(request):
    if request.method=='POST':
        email=request.POST['email']
        if account.objects.filter(email=email).exists():
            user=account.objects.get(email__iexact=email)
            current_site=get_current_site(request)
            mail_subject='Forgot Password Verification'
            message=render_to_string('accounts/forgot_password_verification.html',{
                'user':user,
                'domain':current_site,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user),})
            to_email=email
            send_mail=EmailMessage(mail_subject,message,to=[to_email])
            send_mail.send()
            messages.success(request,'A reset password verification email has been sent to your email address')
            return redirect('login')
        else:
            messages.error(request,'email does not exist')
            return redirect('forgotpassword')
    return render(request,'accounts/forgotpassword.html')

def reset_password_validate(request,uid64,token):
    try:
        uid=urlsafe_base64_decode(uid64).decode()
        user=account._default_manager.get(pk=uid)
    except(ValueError,OverflowError,TypeError,account.DoesNotExist):
        user=None

    if user is not None and default_token_generator.check_token(user,token):
        request.session['uid']=uid
        messages.success(request,'Reset Your Password')
        return redirect('resetpassword')
    else:
        messages.error(request,'Invalid Activation link')
    return redirect('login')




def view_resetpassword(request):
    if request.method=='POST':
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']

        if password==confirm_password:
            uid=request.session.get('uid')
            user=account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request,'password changed successfully!')
            return redirect('login')
        else:
            messages.error(request,'password and confirm password do not match')
            return redirect('resetpassword')
    return render(request,'accounts/resetpassword.html')


@login_required(login_url='login')
def view_dashboard(request):
    orders=order.objects.order_by('created_at').filter(user=request.user,is_ordered=True)
    order_count=orders.count()
    try:
        userprofile=UserProfile.objects.get(user=request.user)
    except:
        userprofile=None
    context={'orders':orders,'order_count':order_count,'userprofile':userprofile}
    return render(request,'accounts/dashboard.html',context)

def view_myorders(request):
    Order=order.objects.order_by('created_at').filter(user=request.user,is_ordered=True)
    context={'Order':Order}
    return render(request,'accounts/myorders.html',context)

def view_orderdetail(request,order_number):
    Order=order.objects.get(order_number=order_number)
    Order_product=orderdetail.objects.filter(order_id=Order.id)
    sub_total=0
    for orders in Order_product:
        sub_total+=orders.product.price*orders.quantity
    context={'order_product':Order_product,'sub_total':sub_total,'order':Order}
    return render(request,'accounts/orderdetails.html',context)


@login_required(login_url='login')
def view_editprofile(request):
        userprofile=get_object_or_404(UserProfile,user=request.user)
        if request.method=='POST':
            userform=userForms(request.POST,instance=request.user)
            userprofileform=UserProfileForm(request.POST,request.FILES,instance=userprofile)
            if userform.is_valid() and userprofileform.is_valid():
                userform.save()
                userprofileform.save()
                messages.success(request,'Your profile has been successfully updated')
                return redirect('editprofile')
        else:
            userform=userForms(instance=request.user)
            userprofileformm=UserProfileForm(instance=userprofile)  
        context={'userforms':userform,'userprofileforms':userprofileformm,'userprofile':userprofile}
        return render(request,'accounts/edit_profile.html',context)

@login_required(login_url='login')
def view_changepassword(request):
    if request.method=='POST':
        current_password=request.POST['current_password']
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']

        user=account.objects.get(username__exact=request.user.username)
        if password==confirm_password:
            success=user.check_password(current_password)
            if success:
                user.set_password(password)

templates/accounts/account_verification.html
{% autoescape off %}
Hi,{{user.first_name}}
Please click on below link to confirm your registeration
http://{{domain}}{% url 'activate' uid64=uid token=token %}
Please ignore,if you think it's not you!!!
{% endautoescape %}

templates/accounts/changepassword.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
        
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Logged in as:</strong> {{userprofile.user.full_name}}
              
            </header>
            <form method="POST" action="{% url 'change_password' %}">
                {% csrf_token %}
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-12 mb-6">
                        <div class="card">
                            <div class="card-body mb-4">  
                                <div class="form-row">
                                    <div class="form-group col" >
                                        <label>Enter Current Password</label>
                                        <input type="password" class="form-control" name="current_password" placeholder="enter Current Password">
                                    </div>


                                </div>
                                <div class="form-row">
                                    <div class="form-group col">
                                        <label>Enter Password</label>
                                        <input type="password" class="form-control" name="password" placeholder="enter Password">
                                    </div>
                                    <div class="form-group col">
                                        <label>Enter confirm password</label>
                                        <input type="password" class="form-control" name="confirm_password" placeholder= "enter confirm Password">
                                    </div>
                                </div>
                                {% include 'includes/alerts.html' %}
                                <div class="form-row">
                                    <button type="submit" class="btn btn-primary">
                                    Submit
                                    </button>
                                </div>
                       
                   
                       
                       
                        </div>
                    </div>
                  
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
        </form>
          
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>






{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
        
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Logged in as:</strong> {{request.user.full_name}}
              
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-6 mb-6">
                        <div class="card">
                            <div class="card-body mb-4">   <center><h3>Total Orders</h3>
                        <h3>{{order_count}}</h3>
                    <a href="{% url 'myOrders' %}">View Orders</a></center>   </div>
                       
                       
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body"><center><img src="{{userprofile.profile_picture.url}}" width='50' style="border-radius:50%"><p>{{request.user.email}}</p><p>{{request.user.phone}}</p></center></div>
                        </div>
                       
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
          
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>




{% endblock %}

templates/accounts/dynamic_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Form</title>
    <style>
        table {
            width: 50%;
            margin: 20px 0;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
    </style>
</head>
<body>
    <h1>Dynamic Form</h1>
    <form method="post">
        {% csrf_token %}
        <table id="dynamicTable">
            <tr>
                <th>From</th>
                <th>To</th>
            </tr>
            <tr>
                <td><input type="number" id="from_initial" name="from_initial" value="{{ initial_from_value }}"></td>
                <td><input type="number" id="to_initial" name="to_initial" value="{{ initial_to_value }}"></td>
            </tr>
        </table>
        <button type="button" id="addRowButton">Add Row</button>
        <br><br>
        <input type="submit" value="Submit">
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var addRowButton = document.getElementById('addRowButton');
            var table = document.getElementById('dynamicTable');

            addRowButton.addEventListener('click', function() {
                var initialFromValue = parseFloat(document.getElementById('from_initial').value);
                var initialToValue = parseFloat(document.getElementById('to_initial').value);
                var gap = initialToValue - initialFromValue;

                var lastRow = table.rows[table.rows.length - 1];
                var lastToValue = parseFloat(lastRow.cells[1].children[0].value);

                var newFromValue = lastToValue;
                var newToValue = newFromValue + gap;

                var newRow = table.insertRow(-1); // Add row at the end
                var cell1 = newRow.insertCell(0);
                var cell2 = newRow.insertCell(1);

                cell1.innerHTML = `<input type="number" name="from_final" value="${newFromValue}" readonly>`;
                cell2.innerHTML = `<input type="number" name="to_final" value="${newToValue}">`;
            });
        });
    </script>
</body>
</html>

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
        
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
               
            </header>
            <div class="card-body">
                <div class="text-right"><img src="{{userprofile.profile_picture.url}}" alt='image loading' width=150 style='border-radius:50%' ></div>
                <!-- <div class="text-right"><img src="{{userprofile.profile_picture.url}}" alt="insert profile_picture"></div> -->
                <div class="row"> 
                    <div class="col-md-12">
                       <form method="POST" action="{% url 'editprofile' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                            <label>First Name</label>
                            {{userforms.first_name}}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Last Name</label>
                            {{userforms.last_name}}
                        </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Phone</label>
                                {{userforms.phone}}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Profile picture</label>
                                {{userprofileforms.profile_picture}}
                            </div>
                        </div>
                        
                        
                            
                            <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Address Line 1</label>
                                {{userprofileforms.address_line_1}}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Address Line 1</label>
                                {{userprofileforms.address_line_2}}
                                
                                    </div>
                                    </div>
                        
                                    <div class="form-row">
                                        <div class="form-group col-md-3">
                                            <label>State</label>
                                            {{userprofileforms.state}}
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>City</label>
                                            {{userprofileforms.city}}
                                            
                                                </div>
                                                <div class="form-group col-md-3">
                                                    <label>Country</label>
                                                    {{userprofileforms.country}}
                                                    
                                                        </div>
                                                </div>
                                                {% include 'includes/alerts.html' %}
                                                <div class="form-row">
        
                                                    <div class="col-md-12">  <button type="submit" class="btn btn-primary">Submit</button></div>
                                              
                                                </div>
                   
            
                       </form>
                    </div>
                   
                       
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
          
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>   
        

{% endblock %}

templates/accounts/forgot_password_verification.html
{% autoescape off %}
Hi,{{user.first_name}}
As per requested, please click on below link to reset your password
http://{{domain}}{% url 'reset_password_validate' uid64=uid token=token %}
If you thimk its not you,Please ignore this mail
{% endautoescape %}

templates/accounts/forgotpassword.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
   <div class="card-body">
   <h4 class="card-title mb-4">Forgot Password</h4>
<form action="{% url 'forgotpassword' %}" method="POST">
    {% csrf_token %}
   
      <div class="form-group">
         <input type="email" class="form-control" placeholder="Email Address" name="email">
<br/><br/>
{% include 'includes/alerts.html' %}
         <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit </button>
        </div> <!-- form-group// -->    
      </div> <!-- form-group// -->
   </div> <!-- card-body.// -->
</div> <!-- card .// -->

 <p class="text-center mt-4">Got Password?<a href="{% url 'login' %}">Sign up</a></p>
 <br><br>
</form>
{% endblock %}

templates/accounts/location.html
<!DOCTYPE html>
<html>
<head>
    <title>Suggest Location</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <h1>Suggest Location</h1>
    <form id="suggestion-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Get Suggestions</button>
    </form>
    <div id="suggestions">
        <h2>Suggestions</h2>
        <label for="id_state">State:</label>
        <select id="id_state"></select>
        <br>
        <label for="id_city">City:</label>
        <select id="id_city"></select>
    </div>
    <script>
        $(document).ready(function() {
            $('#id_country').change(function() {
                var url = "{% url 'load_states' %}";
                var countryId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'country': countryId
                    },
                    success: function(data) {
                        $("#id_state").html('<option value="">Select state</option>');
                        $("#id_city").html('<option value="">Select city</option>');
                        $.each(data, function(key, value) {
                            $("#id_state").append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });

            $('#id_state').change(function() {
                var url = "{% url 'load_cities' %}";
                var stateId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'state': stateId
                    },
                    success: function(data) {
                        $("#id_city").html('<option value="">Select city</option>');
                        $.each(data, function(key, value) {
                            $("#id_city").append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });
        });
    </script>
</body>
</html>