greatKartt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('great.urls')),
    path('',view_home,name='home'),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('kart/',include('kart.urls')),
    path('orders/',include('orders.urls')),
    path('chart/',view_chart)

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

kart/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('addkart/<int:product_id>/',add_kart,name='add_to_kart'),
    path('cart/',cart_details,name='cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',remove_cart_item,name='remove_item'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',remove_cart,name='remove_cart'),
    path('checkout/',view_checkout,name='checkout'),
]

store/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('',view_store,name='store'),
    path('category/<slug:category_slug>/',view_store,name='categories_det'),
    path('category/product_det/<slug:category_slug>/<slug:slug>/',product_detail,name='product_det'),
    path('search/',search,name='search'),
    path('review_rating/<int:productid>/',review_rating,name='reviewrating')
]

store/models.py
from django.db import models 
from great.models import categories
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from accounts.models import *
from django.db.models import Avg,Count

# Create your models here.
class Products(models.Model):
    product_name=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(max_length=100,unique=True)
    description=models.TextField(max_length=100,blank=True)
    price=models.IntegerField()
    images=models.ImageField(upload_to='store/products')
    stock=models.IntegerField()
    categories=models.ForeignKey(categories,on_delete=models.CASCADE)
    is_available=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name='Product'
        verbose_name_plural='Products'


    def get_url(self):
        return reverse('product_det',args=[self.categories.slug,self.slug])


    def average_review(self):
        reviewrating=ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviewrating['average'] is not None:
            avg=float(reviewrating['average'])
        return avg
        
    def average_count(self):
        avgcount=ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count=0
        if avgcount['count'] is not None:
            count=int(avgcount['count'])
        return count

    def __str__(self):
        return self.product_name


class variationmanager(models.Manager):
    def colors(self):
        return super(variationmanager,self).filter(variation_category='colors')
    def sizes(self):
        return super(variationmanager,self).filter(variation_category='sizes')

    
    
        
variation_category_choice=(
    ('colors','colors'),
    ('sizes','sizes'),
     
)
class variations(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    variation_category=models.CharField(max_length=100,choices=variation_category_choice)
    variation_value=models.CharField(max_length=100)
    is_Active=models.BooleanField(default=True)   
    created_date=models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name='variation'
        verbose_name_plural='variations'
    objects=variationmanager()


    def __str__(self):
        return self.variation_value


class ProductGallery(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE,default=None)
    images=models.ImageField(upload_to='photos/products',max_length=100)


    class Meta:
        verbose_name='ProductGallery'
        verbose_name_plural='ProductGalleries'


    def __str__(self):
        return self.product.product_name

class ReviewRating(models.Model):
    user=models.ForeignKey(account,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    subject=models.CharField(blank=True,max_length=100)
    review=models.TextField(blank=True,max_length=100)
    rating=models.FloatField()
    ip=models.CharField(blank=True,max_length=100)
    status=models.BooleanField(default=True)
    created_at=models.DateTimeField(auto_now=True)
    updated_at=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.subject

store/forms.py
from django import forms
from .models import *

class ReviewRatingForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=['subject','review','rating']
        

store/views.py
from django.shortcuts import render,redirect
from great.models import *
from .models import *
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from orders.models import *



# Create your view
def view_store(request,category_slug=None):
    products=None
    if category_slug!=None:
        category=get_object_or_404(categories,slug=category_slug)
        products=Products.objects.filter(categories=category,is_available=True).order_by('id')
        paginator=Paginator(products,2)
        page_number=request.GET.get('page') 
        paged_obj=paginator.get_page(page_number)
        last_page=paged_obj.paginator.num_pages
        product_count=products.count()     
    else:
        products=Products.objects.all().filter(is_available=True).order_by('id')
        paginator=Paginator(products,2)
        page_number=request.GET.get('page')
        paged_obj=paginator.get_page(page_number)
        last_page=paged_obj.paginator.num_pages
        product_count=products.count()
    context={'products':products,'product_count':product_count,'page_list':[n+1 for n in range (last_page)],'last_page':last_page,'products':paged_obj}
    return render(request,'store/store.html',context)


def product_detail(request,category_slug,slug):
    single_product=Products.objects.get(categories__slug=category_slug,slug=slug)
    if request.user.is_authenticated:
        try:
            orderProduct=orderdetail.objects.filter(user=request.user,product_id=single_product.id).exists()
        except orderdetail.DoesNotExist:
            orderProduct=None
    else:
        orderProduct=None

    reviews=ReviewRating.objects.filter(product_id=single_product.id,status=True)
    product_gallery=ProductGallery.objects.filter(product_id=single_product.id)
    context={'single_product':single_product,'product_gallery':product_gallery,'orderproduct':orderProduct,'review':reviews}
    return render(request,'store/product_det.html',context)


def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']

        if keyword:
            products=Products.objects.order_by('created_date').filter(Q(description__icontains=keyword)|Q(product_name__icontains=keyword))
            product_count=products.count()
    context={'products':products,'product_count':product_count,}
    return render(request,'store/store.html',context)

@login_required(login_url='login')
def review_rating(request,productid):
    url=request.META.get('HTTP_REFERER')
    print(url)
    # product=Products.objects.get(id=productid)
    try:
        review=ReviewRating.objects.get(user=request.user,product_id=productid)
        if request.method=='POST':
            forms=ReviewRatingForm(request.POST,instance=review)
            if forms.is_valid():
                forms.save()
                messages.success(request,"review has been successfully updated!")
                return redirect(url)
    except ReviewRating.DoesNotExist:
        forms=ReviewRatingForm(request.POST)
        if forms.is_valid():
            data=ReviewRating()
            data.user=request.user
            data.product_id=productid
            data.subject=forms.cleaned_data['subject']
            data.review=forms.cleaned_data['review']
            data.rating=forms.cleaned_data['rating']
            data.ip=request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request,'review has been successfully saved!')
            return redirect(url)

    



    

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->

    {% if not cart_items %}
    <h3><center>Your cart is empty</center></h3>
    <center><a href="{% url 'store' %}" class="btn btn-danger">Continue Shopping</a></center>

    {% else %}
    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
        {% for item in cart_items %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{item.product.images.url}}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="#" class="title text-dark">{{item.product.product_name}}</a>
                    {% if item.variations.all %}
                    
                    {% for i in item.variations.all %}

                    <p class="text-muted small">{{i.variation_category|capfirst}} : {{i.variation_value|capfirst}}</p>
                    {% endfor %}
                    {% endif %}
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                        <a href="{% url 'remove_item' item.product_id item.id %}" class="btn btn-light" type="button" id="button-minus">   <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{item.quantity}}">
                                <div class="input-group-append">
                                <form action="{% url 'add_to_kart' item.product_id %}" method="POST">
                                    {% csrf_token %}
                                    {% for i in item.variations.all %}
                                    <input type="hidden" name="{{i.variation_category|lower }}" value="{{i.variation_value|capfirst}}"/>
                                    {% endfor %} 
                                    <button type="submit" class="btn btn-light" id="button-plus"><i class="fa fa-plus"></i> </button>
                            
                            </form>
                        </div>
                            </div> <!-- input-group.// -->
                      
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">${{total}}</var> 
                <small class="text-muted"> ${{item.product.price}} each </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'remove_cart' item.product_id item.id %}" onclick = "return confirm('Are you sure you want to delete?')" class="btn btn-danger" > Remove</a>
        </td>
    </tr>
   
    {% endfor %}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{grand_total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    {% endif %}
    
    </div> <!-- container .//  -->
    </section>
    
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->

   
    
    <div class="row">
        <aside class="col-lg-7">
    <h1>Billing Address</h1>
    <form action="{% url 'order' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class ="col form-group">
                <label for="">First Name</label>
                <input type="text" class="form-control" name="first_name" >
            </div>
            <div class="col form-group"><label for="">Last Name</label>
            <input type="text" name="last_name" class="form-control" ></div>
        </div>

        <div class="form-row">
            <div class="col form-group">
            <label>Email</label><input type="text" name="email" class="form-control">
            </div>

            <div class="col form-group">
                <label for="">Phone</label>
                <input type="text" name="phone" class="form-control"> </div>
        </div>
        <div class="form-row">
            <div class="col form-group"><label for="">Address Line 1</label>
            <input type="text" name="address_line_1" class="form-control"></div>

            <div class="col form-group">
                <label for="">Adress line 2</label>
                <input type="text" class="form-control" name="address_line_2">
            </div>
        </div>
        <div class="form-row">
            <div class="col form-group">
                <label for="">state</label>
            <input type="text" name="state" class="form-control">  </div>
            <div class="col form-group">
                <label for="">city</label>
                <input type="text" name="city" class="form-control">
            </div>

            <div class="col form-group">
                <label for="">Country</label>
                <input type="text" class="form-control" name="country">
            </div>


        </div>
        <div class="form-row">
            <div class="col form-group">
                <label for="">order Note</label>
                <textarea cols="2" rows="2" name="order_note" class="form-control"></textarea>
            </div>
        </div>
    
        </aside> <!-- col.// -->
        <aside class="col-lg-5">
    
            <div class="card">
            <div class="card-body">
                <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                      <th scope="col" class="text-right" width="200"> </th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{item.product.images.url}}" class="img-sm"></div>
                                <figcaption class="info">
                                    <a href="#" class="title text-dark">{{item.product.product_name}}</a>
                                    {% if item.variations.all %}
                                    
                                    {% for i in item.variations.all %}
                
                                    <p class="text-muted small">{{i.variation_category|capfirst}} : {{i.variation_value|capfirst}}</p>
                                    {% endfor %}
                                    {% endif %}
                                </figcaption>
                            </figure>
                        </td>
                        <td> 
                            <!-- col.// -->
                         <input type="text" class="form-control"  value="{{item.quantity}}">           
                        </td>
                        <td> 
                            <div class="price-wrap"> 
                                <var class="price">${{item.sub_total}}</var> 
                                <small class="text-muted"> ${{item.product.price}} each </small> 
                            </div> <!-- price-wrap .// -->
                        </td>
                       
                    </tr>
                   
                    {% endfor %}
                    </tbody>
                    </table>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <button type="submit"class="btn btn-primary btn-block">Place Order</button>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
        </form>
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    
    </div> <!-- container .//  -->
    </section>

{% endblock %}

templates/store/product_det.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <center><div class="img-big-wrap mainImage">
        <img src="{{single_product.images.url}}">   </div> </center></article> 
      <!-- img-big-wrap.// -->

        <ul class="thumb">
            <li><a href="{{single_product.images.url}}" target="mainImage"><img src="{{single_product.images.url}}"></a>
          {% for i in  product_gallery %}
            <a href="{{i.images.url}}" target="mainImage"><img src="{{i.images.url}}"></a>
            {% endfor  %}</li>
        </ul>
    </aside>
   <!-- gallery-wrap .end// -->
            
            <main class="col-md-6 border-left">
                <form action="{% url 'add_to_kart' single_product.id %}" method="POST">
                    {% csrf_token %}
    <article class="content-body">
    
    <h2 class="title">{{single_product.product_name}}</h2>
    <div class="rating-star">
        <span>
    <i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif single_product.average_review >= 0.5 and single_product.average_review < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif single_product.average_review >= 1.5 and single_product.average_review < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif single_product.average_review >= 2.5 and single_product.average_review < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif single_product.average_review >= 3.5 and single_product.average_review < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
    <i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif single_product.average_review >= 4.5 and single_product.average_review < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
</span>  </div>
    
    <div class="mb-3"> 
        <var class="price h4">${{single_product.price}}</var> 
    </div> 
    
    <p>{{single_product.description}}</p>
    
    
    <hr>
    <div class="row">
        <div class="item-option-select">
            <h6>Select Size</h6>
        <select name="sizes"  class="form-control" required>
            <option value="" disabled selected>Select sizes</option>
            {% for i in single_product.variations_set.sizes %}
            <option value="{{i.variation_value|lower}}">{{i.variation_value|capfirst}}</option>
            {% endfor %}
        </select>
        
        </div>
    </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6> 
                    <select name ="colors" class="form-control" required>
                      <option value="" disabled selected>Select Colors</option>
                      {% for i in single_product.variations_set.colors %}
                      <option value="{{i.variation_value|lower}}">{{i.variation_value|capfirst}}</option>
                      {% endfor %}
                    </select>
            </div>
        </div> <!-- row.// -->
        
        <hr>
        <span class="text"><button type="submit" class="btn btn-primary">Add to cart</span> <i class="fas fa-shopping-cart "></i> </button>
    </article> <!-- product-info-aside .// --></form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
        </div> <!-- card.// -->
   
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    <form method="POST"  action="{% url 'reviewrating' single_product.id %}">
        {% csrf_token %}
    <div class="row">
                <div class="col-md-9">
            <header class="section-heading">
                <h5>Write Your Reviews </h5> </header>
                <div><label>How do you rate this product?</label>
                    <br/>
                <div class="rate">
                <input type="radio" name="rating" id="rating10" value="5" required/><label for="rating10" title="5"></label> 
                <input type="radio" name="rating" id="rating9" value="4.5" required/><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" id="rating8" value="4" required/><label for="rating8" title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required/><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" id="rating6" value="3" required/><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required/><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" id="rating4" value="2" required/><label for="rating4" title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required/><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" id="rating2" value="1" required/><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required/><label for="rating1" title="0.5" class="half"></label>
            </div></div>
           
           <div class="form-row">
            <div class="form-group col">
                <label>Review Title:</label>
                <input type="text" class="form-control" name="subject">
            </div></div>

            <div class="form-row">
                <div class="form-group col">
                    <label>Review:</label>
                    <textarea rows="4" class="form-control" name="review"></textarea>

                </div>
               
            </div>
            {% include 'includes/alerts.html' %}
            {% if request.user.is_authenticated %}
            {% if orderproduct %}
            <button type="submit" class="btn btn-primary">Submit</button>
            {% else %}
            <p>User should purchase this product to post the review </p>
            {% endif %}
            {% else %}
            <p>User should be login to post the review <a href="{% url 'login'  %}">Login here</a></p>       
            {% endif %}
           
        </form>
        <br/>
            <h1>Customer Reviews</h1>
            <div class="rating-star">
                <span>
            <i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif single_product.average_review >= 0.5 and single_product.average_review < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif single_product.average_review >= 1.5 and single_product.average_review < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif single_product.average_review >= 2.5 and single_product.average_review < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif single_product.average_review >= 3.5 and single_product.average_review < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif single_product.average_review >= 4.5 and single_product.average_review < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
        </span>  <span style="color:black">{{single_product.average_count}} reviews</span>  </div>
            
            

          

            <article class="box mb-3">
                <table>
                    {% for reviews in review %}
                    <tr>
                    <tr>
                    <td><div class="rating-star">
                        <span>
                        <i class="fa fa-star{% if reviews.rating == 0.5 %}-half-o{% elif reviews.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if reviews.rating == 1.5 %}-half-o{% elif reviews.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if reviews.rating == 2.5 %}-half-o{% elif reviews.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if reviews.rating == 3.5 %}-half-o{% elif reviews.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if reviews.rating == 4.5 %}-half-o{% elif reviews.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>               
                    </span></div></td><th  class="text-right"><div>{{reviews.created_at}}</div></th></tr>
                    <tr><td>{{reviews.subject}}</td></tr>
                    <tr><td>{{reviews.review}}</td></tr></tr>
                    {% endfor %}
                </table>
               
                
               
            </article>
        
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>

{% endblock %}